"""
github_pusher.py
----------------
Handles all GitHub operations for the Autonomous AI Dev Agent:
  1. Creates a feature branch from main (feature/SCRUM-5)
  2. Pushes AI-generated code as a file to that branch
  3. Opens a Pull Request automatically
"""

import os
import base64
from github import Github, GithubException
from dotenv import load_dotenv

load_dotenv()

GITHUB_TOKEN    = os.getenv("GITHUB_TOKEN")
GITHUB_USERNAME = os.getenv("GITHUB_USERNAME")
GITHUB_REPO     = os.getenv("GITHUB_REPO")


def get_repo():
    """Authenticate with GitHub and return the target repository object."""
    g = Github(GITHUB_TOKEN)
    repo = g.get_repo(f"{GITHUB_USERNAME}/{GITHUB_REPO}")
    print(f"✅ Connected to GitHub repo: {repo.full_name}")
    return repo


def create_branch(repo, branch_name: str, base_branch: str = "main") -> bool:
    """
    Create a new branch from base_branch.
    Returns True if created, False if it already exists (safe to continue).
    """
    try:
        base_ref = repo.get_branch(base_branch)
        repo.create_git_ref(
            ref=f"refs/heads/{branch_name}",
            sha=base_ref.commit.sha
        )
        print(f"✅ Branch '{branch_name}' created from '{base_branch}'")
        return True
    except GithubException as e:
        if e.status == 422:  # Branch already exists
            print(f"⚠️  Branch '{branch_name}' already exists — continuing.")
            return False
        raise e


def push_code_to_branch(
    repo,
    branch_name: str,
    file_path: str,
    code: str,
    commit_message: str
) -> str:
    """
    Push the AI-generated code to a file on the feature branch.
    Creates the file if it doesn't exist; updates it if it does.
    Returns the file's GitHub URL.
    """
    try:
        # Try to get existing file (needed for SHA when updating)
        existing = repo.get_contents(file_path, ref=branch_name)
        result = repo.update_file(
            path=file_path,
            message=commit_message,
            content=code,
            sha=existing.sha,
            branch=branch_name
        )
        print(f"✅ Updated '{file_path}' on branch '{branch_name}'")
    except GithubException as e:
        if e.status == 404:
            # File doesn't exist yet — create it
            result = repo.create_file(
                path=file_path,
                message=commit_message,
                content=code,
                branch=branch_name
            )
            print(f"✅ Created '{file_path}' on branch '{branch_name}'")
        else:
            raise e

    file_url = result["content"].html_url
    print(f"📄 File URL: {file_url}")
    return file_url


def open_pull_request(
    repo,
    branch_name: str,
    base_branch: str,
    ticket_id: str,
    ticket_title: str,
    ticket_description: str = ""
) -> str:
    """
    Open a Pull Request from branch_name → base_branch.
    Returns the PR URL.
    """
    pr_title = f"[{ticket_id}] {ticket_title}"
    pr_body = f"""## 🤖 Autonomous AI Dev Agent — Auto-generated PR

**Jira Ticket:** `{ticket_id}`
**Title:** {ticket_title}

### Description
{ticket_description or '_No description provided._'}

---
### Checklist
- [x] Code generated by Groq LLM (llama-3.3-70b-versatile)
- [x] Syntax validated via `ast.parse()` sandbox
- [x] Self-correction loop passed (max 3 retries)
- [ ] Human review recommended before merge

> _This PR was opened automatically by the Autonomous AI Dev Agent._
"""

    try:
        pr = repo.create_pull(
            title=pr_title,
            body=pr_body,
            head=branch_name,
            base=base_branch
        )
        print(f"✅ Pull Request opened: {pr.html_url}")
        return pr.html_url
    except GithubException as e:
        # PR may already exist for this branch
        if e.status == 422:
            print("⚠️  PR already exists for this branch.")
            # Fetch existing PR
            pulls = repo.get_pulls(state="open", head=f"{GITHUB_USERNAME}:{branch_name}")
            for pull in pulls:
                print(f"📎 Existing PR: {pull.html_url}")
                return pull.html_url
        raise e


def push_to_github(
    ticket_id: str,
    ticket_title: str,
    ticket_description: str,
    generated_code: str,
    base_branch: str = "main"
) -> dict:
    """
    Main orchestrator — call this from main.py.

    Args:
        ticket_id:           e.g. "SCRUM-5"
        ticket_title:        e.g. "Build a login page in Flask"
        ticket_description:  Full description from Jira
        generated_code:      The AI-generated Python code string
        base_branch:         Branch to create the feature branch from (default: "main")

    Returns:
        dict with keys: branch_name, file_url, pr_url
    """
    branch_name   = f"feature/{ticket_id.upper()}"
    file_name     = f"{ticket_id.lower().replace('-', '_')}_solution.py"
    commit_msg    = f"feat({ticket_id}): Add AI-generated solution for '{ticket_title}'"

    print(f"\n{'='*55}")
    print(f"  GitHub Push Pipeline — {ticket_id}")
    print(f"{'='*55}")

    repo = get_repo()

    # Step 1: Create feature branch
    create_branch(repo, branch_name, base_branch)

    # Step 2: Push generated code
    file_url = push_code_to_branch(
        repo=repo,
        branch_name=branch_name,
        file_path=file_name,
        code=generated_code,
        commit_message=commit_msg
    )

    # Step 3: Open Pull Request
    pr_url = open_pull_request(
        repo=repo,
        branch_name=branch_name,
        base_branch=base_branch,
        ticket_id=ticket_id,
        ticket_title=ticket_title,
        ticket_description=ticket_description
    )

    print(f"\n🎉 GitHub push complete for {ticket_id}!")
    print(f"   Branch : {branch_name}")
    print(f"   File   : {file_url}")
    print(f"   PR     : {pr_url}")
    print(f"{'='*55}\n")

    return {
        "branch_name": branch_name,
        "file_url":    file_url,
        "pr_url":      pr_url
    }


# ── Quick standalone test ──────────────────────────────────────────────────────
if __name__ == "__main__":
    # Simulate what self_corrector.py would hand us
    sample_code = '''
from flask import Flask, render_template, request, redirect, url_for, session

app = Flask(__name__)
app.secret_key = "supersecretkey"

users = {"admin": "password123"}

@app.route("/")
def home():
    if "user" in session:
        return f"Welcome, {session[\'user\']}! <a href=\'/logout\'>Logout</a>"
    return redirect(url_for("login"))

@app.route("/login", methods=["GET", "POST"])
def login():
    error = None
    if request.method == "POST":
        username = request.form["username"]
        password = request.form["password"]
        if users.get(username) == password:
            session["user"] = username
            return redirect(url_for("home"))
        error = "Invalid credentials. Please try again."
    return render_template("login.html", error=error)

@app.route("/logout")
def logout():
    session.pop("user", None)
    return redirect(url_for("login"))

if __name__ == "__main__":
    app.run(debug=True)
'''.strip()

    result = push_to_github(
        ticket_id="SCRUM-5",
        ticket_title="Build a login page in Flask",
        ticket_description="Create a Flask web app with a login page that authenticates users.",
        generated_code=sample_code
    )

    print("Result:", result)